### ISSUE TITLE
Search by GeoPoints

### ISSUE THREAD

**Issue by pereirapleandro** [VivaReal/search-api#127]
Each _geo_point_ is the composition of two coordinates and is represented by an array of `[longitude,latitude]`.
Actually, we have three implementations of search by GeoPoints:

**POINT** - Search using a single _geo_point_ and _radius_ (in meters)
`filter=address.geoLocation.location POINT [-46.57413483123456,-23.49253207123456] RADIUS 5000`

**VIEWPORT** - Search using a set of two _geo_points_ representing a rectangle
`filter=address.geoLocation.location VIEWPORT [[-46.57413483123456,-23.49253207123456],[-46.67644501123456,-23.57814762123456]]`

**POLYGON** - Search using a set of _geo_points_, representing a polygon. `(min_size=3 and max_size=1000)`
`filter=address.geoLocation.location POLYGON [[-46.70854568481445,-23.59798940040613],[-46.70843839645385,-23.599070878131347],[-46.708824634552,-23.599759086586054],[-46.70936107635498,-23.60074223525656],[-46.70974731445312,-23.601371446537634],[-46.70854568481445,-23.59798940040613]]`

**Comment by pedrolis** [comment]
We are able to close this issue, since the PR #130 contained the implementation we defined for these kind of searches, and the wiki was already updated.
