### ISSUE TITLE
[SearchApi] - Pricing filter is not working as expected

### ISSUE THREAD

**Issue by pedrolis** [VivaReal/search-api#196]
http://search-api-v2.vivareal.com/v2/listings??filter=object.object.field IN ['common'] AND facetString:'A' AND (nested.object.field:'common' AND nested.id>=10 AND nested.id<=20)

When filtering numeric fields inside nested fields with values between [300000, 400000] is returning documents with values out of that range.

**Comment by pedrolis** [comment]
Original query:

```
http://search-api-v2.vivareal.com/v2/listings?filter=address.locationId+IN+%5B%22BR%3ESao+Paulo%3ENULL%3ESao+Paulo%3ECentro%3EConsolacao%22%5D+AND+listingType+EQ+%27USED%27+AND+pricingInfos.price+GTE+300000+AND+pricingInfos.price+LTE+400000+AND+pricingInfos.businessType+IN+%5B%22SALE%22%5D&size=35&from=35&sort=pricingInfos.price+ASC&includeFields=id,pricingInfos
```

**Comment by pereirapleandro** [comment]
Closes by https://github.com/VivaReal/search-api/pull/197
